#!/usr/bin/env python3

import argparse
import json
import os
import re
import sys
import urllib.request


def main():
    args = _init_args()
    print("Getting GitHub issue %i" % args.issue_number)
    data = _get_issue_data(args)
    issue_dir = _issue_dir(data)
    print("Creating %s" % issue_dir)
    _makedir(issue_dir)
    _init_readme(data, issue_dir)
    _init_fix(data, issue_dir)


def _init_args():
    p = argparse.ArgumentParser()
    p.add_argument("issue_number", metavar="NUM", help="Issue number.", type=int)

    return p.parse_args()


def _get_issue_data(args):
    resp = urllib.request.urlopen(
        "http://api.github.com/repos/guildai/guildai/issues/%i" % args.issue_number
    )
    return json.load(resp)


def _issue_dir(issue_data):
    number = issue_data["number"]
    title = _issue_dir_title(issue_data["title"])
    return "%i-%s" % (number, title)


def _issue_dir_title(issue_title):
    return _strip_dashes(re.sub(r"[^a-z0-9]+", "-", issue_title.lower()))


def _strip_dashes(s):
    return s.strip("-")


def _makedir(path):
    try:
        os.makedirs(path)
    except OSError as e:
        if e.errno != 17:
            raise
        raise SystemExit("error: %s exists" % path)


def _init_readme(issue_data, dest_dir):
    _copy_template("README.in.md", os.path.join(dest_dir, "README.md"), issue_data)


def _init_fix(issue_data, dest_dir):
    _copy_template("FIX.in.md", os.path.join(dest_dir, "FIX.md"), issue_data)


def _copy_template(template_path, dest, data):
    if os.path.exists(dest):
        raise SystemExit("error: README.md in %s exists" % dest)
    template = open(template_path).read()
    src = _apply_data_to_template(template, data)
    with open(dest, "w") as f:
        f.write(src)


def _apply_data_to_template(template, data):
    subs = [
        ("<Title from GitHub Issue>", data["title"]),
        ("<Issue ID>", str(data["number"])),
    ]
    applied = template
    for s, repl in subs:
        applied = applied.replace(s, repl)
    return applied


if __name__ == "__main__":
    main()
