#!/bin/bash

set -eu

BASE=/tmp/guild-issue-35
SYS1=$BASE/sys1
SYS2=$BASE/sys2

if [ -e $BASE ]; then
    echo "$BASE exists - delete it first and rerun this script"
fi

cat <<EOF

This script recreates Issue 35 by simulating two systems and an export
of runs from one of the systems to another. After runs are moved, the
original project file is deleted to break any references in the
exported runs to the project.

This issue can be recreated with 0.6.5 and has been resolved in 0.6.6.

EOF

init-dirs() {
    mkdir -p $BASE
    mkdir -p $SYS1/guild-home
    mkdir -p $SYS1/project
    mkdir -p $SYS2/guild-home
    mkdir -p $SYS2/project
    mkdir -p $BASE/export-import
}

init-project() {
    cp guild.yml $SYS1/project/
}

generate-run() {
    printf "==> Generating run on system 1\n\n"
    guild -H $SYS1/guild-home -C $SYS1/project run op -y
}

export-run() {
    printf "==> Exporting run on system 1\n\n"
    guild -H $SYS1/guild-home export $BASE/export-import -y
}

import-run() {
    printf "\n==> Importing run on system 2\n\n"
    guild -H $SYS2/guild-home import $BASE/export-import -y
}

delete-project() {
    printf "\n==> Deleting project on system 1 (breaks project ref)\n\n"
    rm $SYS1/project/guild.yml
}

compare-runs() {
    printf "==> Comparing runs on system 2\n\n"
    guild -H $SYS2/guild-home compare --table
}

init-dirs
init-project
generate-run
export-run
import-run
delete-project
compare-runs
